/*
 * Copyright 2020-2021 NXP
 * All rights reserved.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 */

/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
!!GlobalInfo
product: Pins v9.0
processor: MIMXRT1176xxxxx
package_id: MIMXRT1176DVMAA
mcu_data: ksdk2_0
processor_version: 0.9.6
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */

#include "fsl_common.h"
#include "fsl_iomuxc.h"
#include "pin_mux.h"
#include "fsl_gpio.h"

#include "app_shared.h"
/* FUNCTION ************************************************************************************************************
 * 
 * Function Name : BOARD_InitBootPins
 * Description   : Calls initialization functions.
 * 
 * END ****************************************************************************************************************/
void BOARD_InitBootPins(void) {
 //   BOARD_InitPins();
    BOARD_InitMicPins();
}

/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
BOARD_InitPins:
- options: {callFromInitBoot: 'true', coreID: cm7, enableClock: 'true'}
- pin_list:
  - {pin_num: M15, peripheral: LPUART1, signal: RXD, pin_signal: GPIO_AD_25, software_input_on: Enable, pull_up_down_config: Pull_Down, pull_keeper_select: Pull,
    open_drain: Disable, drive_strength: High, slew_rate: Slow}
  - {pin_num: L13, peripheral: LPUART1, signal: TXD, pin_signal: GPIO_AD_24, software_input_on: Disable, pull_up_down_config: Pull_Down, pull_keeper_select: Pull,
    open_drain: Disable, drive_strength: High, slew_rate: Slow}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitPins, assigned for the Cortex-M7F core.
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/


void BOARD_InitPins_REV2(void) {


  CLOCK_EnableClock(kCLOCK_Iomuxc);           /* LPCG on: LPCG is ON. */
  CLOCK_EnableClock(kCLOCK_Iomuxc_Lpsr);      /* LPCG on: LPCG is ON. */

  /* GPIO configuration of CAMERA_VSYNC on GPIO_AD_20 (pin K13) */
    gpio_pin_config_t CAMERA_VSYNC_config = {
        .direction = kGPIO_DigitalInput,
        .outputLogic = 0U,
        .interruptMode = kGPIO_NoIntmode
    };
    /* Initialize GPIO functionality on GPIO_AD_20 (pin K13) */
    GPIO_PinInit(GPIO3, 19U, &CAMERA_VSYNC_config);
    IOMUXC_SetPinMux(
         IOMUXC_GPIO_AD_20_GPIO_MUX3_IO19,       /* GPIO_AD_20 is configured as GPIO_MUX3_IO19 */
         0U);                                    /* Software Input On Field: Input Path is determined by functionality */

    /* GPIO configuration of TP_13 on GPIO_AD_21 (pin K14) */
      gpio_pin_config_t TP_13_config = {
          .direction = kGPIO_DigitalInput,
          .outputLogic = 0U,
          .interruptMode = kGPIO_NoIntmode
      };
      /* Initialize GPIO functionality on GPIO_AD_20 (pin K13) */
      GPIO_PinInit(GPIO3, 20U, &TP_13_config);
      IOMUXC_SetPinMux(
        IOMUXC_GPIO_AD_21_GPIO_MUX3_IO20,       /* GPIO_AD_21 is configured as GPIO_MUX3_IO20 */
        0U);                                    /* Software Input On Field: Input Path is determined by functionality */


    /* GPIO configuration of UC_STROBE on GPIO_AD_23 (pin J12) */
    gpio_pin_config_t UC_STROBE_config = {
        .direction = kGPIO_DigitalOutput,
        .outputLogic = 0U,
        .interruptMode = kGPIO_NoIntmode
    };
    /* Initialize GPIO functionality on GPIO_AD_23 (pin J12) */
    GPIO_PinInit(GPIO3, 22U, &UC_STROBE_config);
    IOMUXC_SetPinMux(
        IOMUXC_GPIO_AD_23_GPIO_MUX3_IO22,       /* GPIO_AD_23 is configured as GPIO_MUX3_IO22 */
        0U);                                    /* Software Input On Field: Input Path is determined by functionality */

    /* GPIO configuration of CAMERA_SHUTTER_RESET on GPIO_AD_24 (pin L13) */
    gpio_pin_config_t CAMERA_SHUTTER_RESET_config = {
        .direction = kGPIO_DigitalOutput,
        .outputLogic = 0U,
        .interruptMode = kGPIO_NoIntmode
    };
    /* Initialize GPIO functionality on GPIO_AD_24 (pin L13) */
    GPIO_PinInit(GPIO3, 23U, &CAMERA_SHUTTER_RESET_config);
    IOMUXC_SetPinMux(
        IOMUXC_GPIO_AD_24_GPIO_MUX3_IO23,       /* GPIO_AD_24 is configured as GPIO_MUX3_IO23 */
        0U);                                    /* Software Input On Field: Input Path is determined by functionality */

    /* GPIO configuration of CAMERA_SHUTTER_SET on GPIO_AD_25 (pin M15) */
    gpio_pin_config_t CAMERA_SHUTTER_SET_config = {
        .direction = kGPIO_DigitalOutput,
        .outputLogic = 0U,
        .interruptMode = kGPIO_NoIntmode
    };
    /* Initialize GPIO functionality on GPIO_AD_25 (pin M15) */
    GPIO_PinInit(GPIO3, 24U, &CAMERA_SHUTTER_SET_config);
    IOMUXC_SetPinMux(
         IOMUXC_GPIO_AD_25_GPIO_MUX3_IO24,       /* GPIO_AD_25 is configured as GPIO_MUX3_IO24 */
         0U);                                    /* Software Input On Field: Input Path is determined by functionality */


    /* GPIO configuration of CAMERA_PWR_CTL_1V8 on GPIO_AD_26 (pin L14) */
    gpio_pin_config_t CAMERA_PWR_CTL_1V8_config = {
        .direction = kGPIO_DigitalOutput,
        .outputLogic = 0U,
        .interruptMode = kGPIO_NoIntmode
    };
    /* Initialize GPIO functionality on GPIO_AD_26 (pin L14) */
    GPIO_PinInit(GPIO3, 25U, &CAMERA_PWR_CTL_1V8_config);
    IOMUXC_SetPinMux(
       IOMUXC_GPIO_AD_26_GPIO_MUX3_IO25,       /* GPIO_AD_26 is configured as GPIO_MUX3_IO25 */
       0U);                                    /* Software Input On Field: Input Path is determined by functionality */

    /* GPIO configuration of 6V5_ENABLE on GPIO_DISP_B2_12 (pin B6) */
      gpio_pin_config_t ENABLE_6V5_config = {
          .direction = kGPIO_DigitalOutput,
          .outputLogic = 0U,
          .interruptMode = kGPIO_NoIntmode
      };
      /* Initialize GPIO functionality on GPIO_DISP_B2_12 (pin B6) */
      GPIO_PinInit(GPIO5, 13U, &ENABLE_6V5_config);
      IOMUXC_SetPinMux(
           IOMUXC_GPIO_DISP_B2_12_GPIO_MUX5_IO13,  /* GPIO_DISP_B2_13 is configured as GPIO_MUX5_IO13 */
           0U);                                    /* Software Input On Field: Input Path is determined by functionality */

      /* GPIO configuration of CAMERA_FREX on GPIO_DISP_B2_13 (pin A5) */
      gpio_pin_config_t CAMERA_FREX_config = {
          .direction = kGPIO_DigitalOutput,
          .outputLogic = 0U,
          .interruptMode = kGPIO_NoIntmode
      };
      /* Initialize GPIO functionality on GPIO_DISP_B2_13 (pin A5) */
      GPIO_PinInit(GPIO5, 14U, &CAMERA_FREX_config);
      IOMUXC_SetPinMux(
           IOMUXC_GPIO_DISP_B2_13_GPIO_MUX5_IO14,  /* GPIO_DISP_B2_13 is configured as GPIO_MUX5_IO14 */
           0U);                                    /* Software Input On Field: Input Path is determined by functionality */
      IOMUXC_SetPinMux(
          IOMUXC_GPIO_DISP_B2_13_GPIO11_IO14,     /* GPIO_DISP_B2_13 is configured as GPIO11_IO14 */
          0U);                                    /* Software Input On Field: Input Path is determined by functionality */


      /* GPIO configuration of CAMERA_RESET on GPIO_DISP_B2_14 (pin A7) */
      gpio_pin_config_t CAMERA_RESET_config = {
          .direction = kGPIO_DigitalOutput,
          .outputLogic = 0U,
          .interruptMode = kGPIO_NoIntmode
      };
      /* Initialize GPIO functionality on GPIO_DISP_B2_14 (pin A7) */
      GPIO_PinInit(GPIO5, 15U, &CAMERA_RESET_config);
      IOMUXC_SetPinMux(
          IOMUXC_GPIO_DISP_B2_14_GPIO_MUX5_IO15,  /* GPIO_DISP_B2_14 is configured as GPIO_MUX5_IO15 */
          0U);                                    /* Software Input On Field: Input Path is determined by functionality */

#if(1)
      IOMUXC_SetPinMux(						// ts. Not sure this is necessary, this will turn in to an Analog pin.  But just to be sure..
          IOMUXC_GPIO_AD_04_GPIO9_IO03,
          0x0A);
      IOMUXC_SetPinConfig(
    	  IOMUXC_GPIO_AD_04_GPIO9_IO03,
          0x00U);
      	gpio_pin_config_t ANALOG_gpio_config =
      	{
      		.direction = kGPIO_DigitalInput,
			.outputLogic = 0,
			.interruptMode = kGPIO_NoIntmode
      	};
    	GPIO_PinInit(GPIO9, 3, &ANALOG_gpio_config );

        IOMUXC_SetPinMux(					// ts. Not sure this is necessary, this will turn in to an Analog pin.  But just to be sure.
        	IOMUXC_GPIO_AD_00_GPIO8_IO31,
            0x0A);
        IOMUXC_SetPinConfig(
        	IOMUXC_GPIO_AD_00_GPIO8_IO31,
            0x00U);
      	GPIO_PinInit(GPIO8, 31, &ANALOG_gpio_config );

#endif




  IOMUXC_SetPinMux(
      IOMUXC_GPIO_DISP_B1_00_ENET_QOS_RX_EN,  /* GPIO_DISP_B1_00 is configured as ENET_QOS_RX_EN */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_DISP_B1_01_ENET_QOS_RX_CLK,  /* GPIO_DISP_B1_01 is configured as ENET_QOS_RX_CLK */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_DISP_B1_02_ENET_QOS_RX_DATA00,  /* GPIO_DISP_B1_02 is configured as ENET_QOS_RX_DATA00 */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_DISP_B1_03_ENET_QOS_RX_DATA01,  /* GPIO_DISP_B1_03 is configured as ENET_QOS_RX_DATA01 */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_DISP_B1_04_ENET_QOS_RX_DATA02,  /* GPIO_DISP_B1_04 is configured as ENET_QOS_RX_DATA02 */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_DISP_B1_05_ENET_QOS_RX_DATA03,  /* GPIO_DISP_B1_05 is configured as ENET_QOS_RX_DATA03 */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_DISP_B1_06_ENET_QOS_TX_DATA03,  /* GPIO_DISP_B1_06 is configured as ENET_QOS_TX_DATA03 */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_DISP_B1_07_ENET_QOS_TX_DATA02,  /* GPIO_DISP_B1_07 is configured as ENET_QOS_TX_DATA02 */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_DISP_B1_08_ENET_QOS_TX_DATA01,  /* GPIO_DISP_B1_08 is configured as ENET_QOS_TX_DATA01 */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_DISP_B1_09_ENET_QOS_TX_DATA00,  /* GPIO_DISP_B1_09 is configured as ENET_QOS_TX_DATA00 */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_DISP_B1_10_ENET_QOS_TX_EN,  /* GPIO_DISP_B1_10 is configured as ENET_QOS_TX_EN */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_DISP_B1_11_ENET_QOS_TX_CLK,  /* GPIO_DISP_B1_11 is configured as ENET_QOS_TX_CLK */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */

  // Disconnected pins
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_EMC_B2_19_ENET_QOS_MDC,     /* GPIO_EMC_B2_19 is configured as ENET_QOS_MDC */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  // Disconnected pins
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_EMC_B2_20_ENET_QOS_MDIO,    /* GPIO_EMC_B2_20 is configured as ENET_QOS_MDIO */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */


  // LPI2C1 - Phy
    IOMUXC_SetPinMux(
        IOMUXC_GPIO_AD_33_LPI2C1_SDA,         /* GPIO_LPSR_04 is configured as LPI2C5_SDA */
        1U);                                    /* Software Input On Field: Force input path of pad GPIO_LPSR_04 */
    IOMUXC_SetPinConfig(
        IOMUXC_GPIO_AD_33_LPI2C1_SDA,         /* GPIO_LPSR_04 PAD functional properties : */
        0x2CU);                                 /* Slew Rate Field: Slow Slew Rate
                                                   Drive Strength Field: normal driver
                                                   Pull / Keep Select Field: Pull Disable
                                                   Pull Up / Down Config. Field: Weak pull down
                                                   Open Drain LPSR Field: Enabled
                                                   Domain write protection: Both cores are allowed
                                                   Domain write protection lock: Neither of DWP bits is locked */
    IOMUXC_SetPinMux(
        IOMUXC_GPIO_AD_32_LPI2C1_SCL,         /* GPIO_LPSR_05 is configured as LPI2C5_SCL */
        1U);                                    /* Software Input On Field: Force input path of pad GPIO_LPSR_05 */
    IOMUXC_SetPinConfig(
        IOMUXC_GPIO_AD_32_LPI2C1_SCL,         /* GPIO_LPSR_05 PAD functional properties : */
        0x2CU);                                 /* Slew Rate Field: Slow Slew Rate
                                                   Drive Strength Field: normal driver
                                                   Pull / Keep Select Field: Pull Disable
                                                   Pull Up / Down Config. Field: Weak pull down
                                                   Open Drain LPSR Field: Enabled
                                                   Domain write protection: Both cores are allowed
                                                   Domain write protection lock: Neither of DWP bits is locked */



// LPI2C5 - Camera
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_LPSR_04_LPI2C5_SDA,         /* GPIO_LPSR_04 is configured as LPI2C5_SDA */
      1U);                                    /* Software Input On Field: Force input path of pad GPIO_LPSR_04 */
  IOMUXC_SetPinConfig(
      IOMUXC_GPIO_LPSR_04_LPI2C5_SDA,         /* GPIO_LPSR_04 PAD functional properties : */
      0x2CU);                                 /* Slew Rate Field: Slow Slew Rate
                                                 Drive Strength Field: normal driver
                                                 Pull / Keep Select Field: Pull Disable
                                                 Pull Up / Down Config. Field: Weak pull down
                                                 Open Drain LPSR Field: Enabled
                                                 Domain write protection: Both cores are allowed
                                                 Domain write protection lock: Neither of DWP bits is locked */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_LPSR_05_LPI2C5_SCL,         /* GPIO_LPSR_05 is configured as LPI2C5_SCL */
      1U);                                    /* Software Input On Field: Force input path of pad GPIO_LPSR_05 */
  IOMUXC_SetPinConfig(
      IOMUXC_GPIO_LPSR_05_LPI2C5_SCL,         /* GPIO_LPSR_05 PAD functional properties : */
      0x2CU);                                 /* Slew Rate Field: Slow Slew Rate
                                                 Drive Strength Field: normal driver
                                                 Pull / Keep Select Field: Pull Disable
                                                 Pull Up / Down Config. Field: Weak pull down
                                                 Open Drain LPSR Field: Enabled
                                                 Domain write protection: Both cores are allowed
                                                 Domain write protection lock: Neither of DWP bits is locked */
// LPI2C6 - Accel
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_LPSR_06_LPI2C6_SDA,         /* GPIO_LPSR_06 is configured as LPI2C6_SDA */
      1U);                                    /* Software Input On Field: Force input path of pad GPIO_LPSR_06 */
  IOMUXC_SetPinConfig(//T.S. high drive strength 2022 07 25
      IOMUXC_GPIO_LPSR_06_LPI2C6_SDA,         /* GPIO_LPSR_06 PAD functional properties : */
      0x2EU);                                 /* Slew Rate Field: Slow Slew Rate
                                                 Drive Strength Field: normal driver
                                                 Pull / Keep Select Field: Pull Disable
                                                 Pull Up / Down Config. Field: Weak pull down
                                                 Open Drain LPSR Field: Enabled
                                                 Domain write protection: Both cores are allowed
                                                 Domain write protection lock: Neither of DWP bits is locked */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_LPSR_07_LPI2C6_SCL,         /* GPIO_LPSR_07 is configured as LPI2C6_SCL */
      1U);                                    /* Software Input On Field: Force input path of pad GPIO_LPSR_07 */
  IOMUXC_SetPinConfig(//T.S. high drive strength 2022 07 25
      IOMUXC_GPIO_LPSR_07_LPI2C6_SCL,         /* GPIO_LPSR_07 PAD functional properties : */
      0x2EU);                                 /* Slew Rate Field: Slow Slew Rate
                                                 Drive Strength Field: normal driver
                                                 Pull / Keep Select Field: Pull Disable
                                                 Pull Up / Down Config. Field: Weak pull down
                                                 Open Drain LPSR Field: Enabled
                                                 Domain write protection: Both cores are allowed
                                                 Domain write protection lock: Neither of DWP bits is locked */

// LPSPI1

  IOMUXC_SetPinMux(
      IOMUXC_GPIO_AD_28_LPSPI1_SCK,           /* GPIO_AD_28 is configured as LPSPI1_SCK */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinConfig(
      IOMUXC_GPIO_AD_28_LPSPI1_SCK,           /* GPIO_AD_28 PAD functional properties : */
      0x02U);                                 /* Slew Rate Field: Slow Slew Rate
                                                 Drive Strength Field: high drive strength
                                                 Pull / Keep Select Field: Pull Disable, Highz
                                                 Pull Up / Down Config. Field: Weak pull down
                                                 Open Drain Field: Disabled
                                                 Domain write protection: Both cores are allowed
                                                 Domain write protection lock: Neither of DWP bits is locked */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_AD_29_LPSPI1_PCS0,          /* GPIO_AD_29 is configured as LPSPI1_PCS0 */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinConfig(
      IOMUXC_GPIO_AD_29_LPSPI1_PCS0,          /* GPIO_AD_29 PAD functional properties : */
      0x02U);                                 /* Slew Rate Field: Slow Slew Rate
                                                 Drive Strength Field: high drive strength
                                                 Pull / Keep Select Field: Pull Disable, Highz
                                                 Pull Up / Down Config. Field: Weak pull down
                                                 Open Drain Field: Disabled
                                                 Domain write protection: Both cores are allowed
                                                 Domain write protection lock: Neither of DWP bits is locked */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_AD_30_LPSPI1_SOUT,          /* GPIO_AD_30 is configured as LPSPI1_SOUT */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinConfig(
      IOMUXC_GPIO_AD_30_LPSPI1_SOUT,          /* GPIO_AD_30 PAD functional properties : */
      0x02U);                                 /* Slew Rate Field: Slow Slew Rate
                                                 Drive Strength Field: high drive strength
                                                 Pull / Keep Select Field: Pull Disable, Highz
                                                 Pull Up / Down Config. Field: Weak pull down
                                                 Open Drain Field: Disabled
                                                 Domain write protection: Both cores are allowed
                                                 Domain write protection lock: Neither of DWP bits is locked */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_AD_31_LPSPI1_SIN,           /* GPIO_AD_31 is configured as LPSPI1_SIN */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinConfig(
      IOMUXC_GPIO_AD_31_LPSPI1_SIN,           /* GPIO_AD_31 PAD functional properties : */
      0x02U);                                 /* Slew Rate Field: Slow Slew Rate
                                                 Drive Strength Field: high drive strength
                                                 Pull / Keep Select Field: Pull Disable, Highz
                                                 Pull Up / Down Config. Field: Weak pull down
                                                 Open Drain Field: Disabled
                                                 Domain write protection: Both cores are allowed
                                                 Domain write protection lock: Neither of DWP bits is locked */


 // LPUART2
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_DISP_B2_10_LPUART2_TXD,          /* GPIO_DISP_B2_10 is configured as LPUART2_TXD */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinConfig(
	  IOMUXC_GPIO_DISP_B2_10_LPUART2_TXD,          /* GPIO_DISP_B2_10 PAD functional properties : */
      0x02U);                                 /* Slew Rate Field: Slow Slew Rate
                                                 Drive Strength Field: high drive strength
                                                 Pull / Keep Select Field: Pull Disable, Highz
                                                 Pull Up / Down Config. Field: Weak pull down
                                                 Open Drain Field: Disabled
                                                 Domain write protection: Both cores are allowed
                                                 Domain write protection lock: Neither of DWP bits is locked */
  IOMUXC_SetPinMux(
	  IOMUXC_GPIO_DISP_B2_11_LPUART2_RXD,          /* GPIO_DISP_B2_11 is configured as LPUART2_RXD */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinConfig(
	  IOMUXC_GPIO_DISP_B2_11_LPUART2_RXD,          /* GPIO_DISP_B2_11 PAD functional properties : */
      0x02U);                                 /* Slew Rate Field: Slow Slew Rate
                                                 Drive Strength Field: high drive strength
                                                 Pull / Keep Select Field: Pull Disable, Highz
                                                 Pull Up / Down Config. Field: Weak pull down
                                                 Open Drain Field: Disabled
                                                 Domain write protection: Both cores are allowed
                                                 Domain write protection lock: Neither of DWP bits is locked */


	gpio_pin_config_t gpioOutput_config = {
	  .direction = kGPIO_DigitalOutput,
	  .outputLogic = 0U,
	  .interruptMode = kGPIO_NoIntmode
	};
	gpio_pin_config_t gpioInput_config = {
	  .direction = kGPIO_DigitalInput,
	  .outputLogic = 0U,
	  .interruptMode = kGPIO_NoIntmode
	};


// PHY_INT
	/* Initialize GPIO functionality on GPIO_AD_06 (pin N13) */
	GPIO_PinInit(GPIO9, 5U, &gpioInput_config);
	IOMUXC_SetPinMux(
		IOMUXC_GPIO_AD_06_GPIO9_IO05,       /* GPIO_AD_06 is configured as GPIO9_IO05 */
		0U);

// PHY_RESET
	/* Initialize GPIO functionality on GPIO_AD_06 (pin N13) */
	GPIO_PinInit(GPIO9, 8U, &gpioOutput_config);
	IOMUXC_SetPinMux(
		IOMUXC_GPIO_AD_09_GPIO9_IO08,       /* GPIO_AD_09 is configured as GPIO9_IO08 */
		0U);

// PHY_PME_N
	/* Initialize GPIO functionality on GPIO_AD_06 (pin N13) */
	GPIO_PinInit(GPIO9, 21U, &gpioInput_config);
	IOMUXC_SetPinMux(
		IOMUXC_GPIO_AD_22_GPIO9_IO21,       /* GPIO_AD_22 is configured as GPIO9_IO21 */
		0U);



// Visible LED  - LED_SIDE_A_POWER_FAULT
    /* Initialize GPIO functionality on GPIO_DISP_B2_07 (pin D6) */
    GPIO_PinInit(GPIO11, 8U, &gpioOutput_config);
    IOMUXC_SetPinMux(
    	IOMUXC_GPIO_DISP_B2_07_GPIO11_IO08,      /* GPIO_DISP_B2_07 is configured as GPIO_11_IO08 */
        0U);                                    /* Software Input On Field: Input Path is determined by functionality */


// Visible LED  - LED_SIDE_B_POWER_FAULT
    /* Initialize GPIO functionality on GPIO_DISP_B2_09 (pin D8) */
    GPIO_PinInit(GPIO11, 10U, &gpioOutput_config);
    IOMUXC_SetPinMux(
    	IOMUXC_GPIO_DISP_B2_09_GPIO11_IO10,      /* GPIO_DISP_B2_09 is configured as GPIO_11_IO10 */
        0U);                                    /* Software Input On Field: Input Path is determined by functionality */

// Visible LED  - LED_CAMERA
    /* Initialize GPIO functionality on GPIO_AD_05 (pin P13) */
    GPIO_PinInit(GPIO9, 4U, &gpioOutput_config);
    IOMUXC_SetPinMux(
    	IOMUXC_GPIO_AD_05_GPIO9_IO04,       /* GPIO_AD_05 is configured as GPIO9_IO04 */
		0U);                                    /* Software Input On Field: Input Path is determined by functionality */

// Visible LED  - LED_HEARTBEAT
	/* Initialize GPIO functionality on GPIO_AD_08 (pin R15) */
	GPIO_PinInit(GPIO9, 7U, &gpioOutput_config);
	IOMUXC_SetPinMux(
		IOMUXC_GPIO_AD_08_GPIO9_IO07,       /* GPIO_AD_08 is configured as GPIO9_IO07 */
		0U);                                    /* Software Input On Field: Input Path is determined by functionality */

// Visible LED  - LED_SIDE_A_PIR
	/* Initialize GPIO functionality on GPIO_AD_10 (pin R17) */
	GPIO_PinInit(GPIO9, 9U, &gpioOutput_config);
	IOMUXC_SetPinMux(
		IOMUXC_GPIO_AD_10_GPIO9_IO09,       /* GPIO_AD_10 is configured as GPIO9_IO09 */
		0U);                                    /* Software Input On Field: Input Path is determined by functionality */

// Visible LED  - LED_SIDE_B_PIR
	/* Initialize GPIO functionality on GPIO_AD_11 (pin P16) */
	GPIO_PinInit(GPIO9, 10U, &gpioOutput_config);
	IOMUXC_SetPinMux(
		IOMUXC_GPIO_AD_11_GPIO9_IO10,       /* GPIO_AD_11 is configured as GPIO9_IO10 */
		0U);                                    /* Software Input On Field: Input Path is determined by functionality */

// Visible LED  - LED_RADAR
	/* Initialize GPIO functionality on GPIO_AD_19 (pin L16) */
	GPIO_PinInit(GPIO9, 18U, &gpioOutput_config);
	IOMUXC_SetPinMux(
		IOMUXC_GPIO_AD_19_GPIO9_IO18,       /* GPIO_AD_19 is configured as GPIO9_IO18 */
		0U);                                    /* Software Input On Field: Input Path is determined by functionality */

// Visible LED  - LED_ACCEL
	/* Initialize GPIO functionality on GPIO_AD_27 (pin N16) */
	GPIO_PinInit(GPIO9, 26U, &gpioOutput_config);
	IOMUXC_SetPinMux(
		IOMUXC_GPIO_AD_27_GPIO9_IO26,       /* GPIO_AD_26 is configured as GPIO9_IO26 */
		0U);                                    /* Software Input On Field: Input Path is determined by functionality */

// IR LED  - Strobe on.
	/* Initialize GPIO functionality on GPIO_AD_23 (pin J12) */
	GPIO_PinInit(GPIO9, 22U, &gpioOutput_config);
	IOMUXC_SetPinMux(
		IOMUXC_GPIO_AD_23_GPIO9_IO22,       /* GPIO_AD_26 is configured as GPIO9_IO26 */
		1U);                                    /* Software Input On Field: Input Path is determined by functionality */

// EFUSE  - FLT_A
	/* Initialize GPIO functionality on GPIO_AD_03 (pin P15) */
	GPIO_PinInit(GPIO9, 2U, &gpioInput_config);
	IOMUXC_SetPinMux(
		IOMUXC_GPIO_AD_03_GPIO9_IO02,       /* GPIO_AD_03 is configured as GPIO9_IO02 */
		0U);                                    /* Software Input On Field: Input Path is determined by functionality */
// EFUSE  - FLT_B
	/* Initialize GPIO functionality on GPIO_AD_17 (pin N15) */
	GPIO_PinInit(GPIO9, 16U, &gpioInput_config);
	IOMUXC_SetPinMux(
		IOMUXC_GPIO_AD_17_GPIO9_IO16,       /* GPIO_AD_03 is configured as GPIO9_IO02 */
		0U);                                    /* Software Input On Field: Input Path is determined by functionality */

// EFUSE  - SHDN_A
	/* Initialize GPIO functionality on GPIO_AD_07 (pin T17) */
	GPIO_PinInit(GPIO9, 6U, &gpioOutput_config);
	IOMUXC_SetPinMux(
		IOMUXC_GPIO_AD_07_GPIO9_IO06,       /* GPIO_AD_07 is configured as GPIO9_IO06 */
		0U);                                    /* Software Input On Field: Input Path is determined by functionality */
// EFUSE  - SHDN_B
	/* Initialize GPIO functionality on GPIO_AD_01 (pin R14) */
	GPIO_PinInit(GPIO9, 0U, &gpioOutput_config);
	IOMUXC_SetPinMux(
		IOMUXC_GPIO_AD_01_GPIO9_IO00,       /* GPIO_AD_01 is configured as GPIO9_IO00 */
		0U);                                    /* Software Input On Field: Input Path is determined by functionality */

// External Watchdog

// NO!  don't do this here.  Tristate state is 'disable' to the watchdog.  We want this disabled for now.
	/* Initialize GPIO functionality on GPIO_DISP_B2_15 (pin A4) */
//	GPIO_PinInit(GPIO5, 16U, &gpioOutput_config);
	IOMUXC_SetPinMux(
		IOMUXC_GPIO_DISP_B2_15_GPIO_MUX5_IO16,       /* GPIO_DISP_B2_15 is configured as GPIO5_IO16 */
		0U);                                    /* Software Input On Field: Input Path is determined by functionality */
// INSTEAD... set it as an input.  this makes the pin tristate.  Need to turn this to an output before use.
	GPIO_PinInit(GPIO5, 16U, &gpioInput_config);

// Setting RESET Push Button
	/* Initialize GPIO functionality on GPIO_LPSR_00 (pin N6) */
	GPIO_PinInit(GPIO6, 0U, &gpioInput_config);
	IOMUXC_SetPinMux(
		IOMUXC_GPIO_LPSR_00_GPIO_MUX6_IO00,       /* GPIO_LPSR_00 is configured as GPIO6_IO0 */
		0U);                                    /* Software Input On Field: Input Path is determined by functionality */
	IOMUXC_SetPinConfig(IOMUXC_GPIO_LPSR_00_GPIO_MUX6_IO00,IOMUXC_SW_PAD_CTL_PAD_PULL(1) | IOMUXC_SW_PAD_CTL_PAD_PUS(1));		// turn on weak pull up.



	// GPIO09.14 = PIR1, Direct Link.
	GPIO_PinInit(GPIO9, 14U, &gpioOutput_config);
	IOMUXC_SetPinMux(
			IOMUXC_GPIO_AD_15_GPIO9_IO14,
			0U);                                    /* Software Input On Field: Input Path is determined by functionality */
	IOMUXC_SetPinConfig(
			IOMUXC_GPIO_AD_15_GPIO9_IO14,          /* GPIO_DISP_B2_11 PAD functional properties : */
			0x0EU);                                 // High drive strength, PU enabled.
	GPIO_PinWrite(GPIO9, (14U), 0U);

// GPIO09.1 = PIR1, Serial Link.
	GPIO_PinInit(GPIO9, 1U, &gpioOutput_config);
	IOMUXC_SetPinMux(
			IOMUXC_GPIO_AD_02_GPIO9_IO01,
			0U);                                    /* Software Input On Field: Input Path is determined by functionality */
	IOMUXC_SetPinConfig(
			IOMUXC_GPIO_AD_02_GPIO9_IO01,          /* GPIO_DISP_B2_11 PAD functional properties : */
			0x02U);                                 // High drive strength.

// GPIO09.15 = PIR2, Direct Link.
	GPIO_PinInit(GPIO9, 15U, &gpioOutput_config);
	IOMUXC_SetPinMux(
			IOMUXC_GPIO_AD_16_GPIO9_IO15,
			0U);                                    /* Software Input On Field: Input Path is determined by functionality */
	IOMUXC_SetPinConfig(
			IOMUXC_GPIO_AD_16_GPIO9_IO15,          /* GPIO_DISP_B2_11 PAD functional properties : */
			0x0EU);                                 // High drive strength, PU enabled.
	GPIO_PinWrite(GPIO9, (15U), 0U);

// GPIO011.9 = PIR2, Serial Link.
	GPIO_PinInit(GPIO11, 9U, &gpioOutput_config);
	IOMUXC_SetPinMux(
			IOMUXC_GPIO_DISP_B2_08_GPIO11_IO09,
			0U);
	IOMUXC_SetPinConfig(
			IOMUXC_GPIO_DISP_B2_08_GPIO11_IO09,          /* GPIO_DISP_B2_11 PAD functional properties : */
			0x02U);                                 // High drive strength.


// HF MEMS - CLK - PDM
	IOMUXC_SetPinMux(
	  IOMUXC_GPIO_LPSR_08_MIC_CLK,            /* GPIO_LPSR_08 is configured as MIC_CLK */
	  0U);                                    /* Software Input On Field: Input Path is determined by functionality */
	IOMUXC_SetPinConfig(
	  IOMUXC_GPIO_LPSR_08_MIC_CLK,            /* GPIO_LPSR_08 PAD functional properties : */
	  0x03U);                                 /* Slew Rate Field: Fast Slew Rate
												 Drive Strength Field: high driver
												 Pull / Keep Select Field: Pull Disable
												 Pull Up / Down Config. Field: Weak pull down
												 Open Drain LPSR Field: Disabled
												 Domain write protection: Both cores are allowed
												 Domain write protection lock: Neither of DWP bits is locked */

// HF MEMS - BITSTREAM0 - PDM
	IOMUXC_SetPinMux(
	  IOMUXC_GPIO_LPSR_09_MIC_BITSTREAM0,     /* GPIO_LPSR_09 is configured as MIC_BITSTREAM0 */
	  0U);                                    /* Software Input On Field: Input Path is determined by functionality */


	IOMUXC_SetPinConfig(
	  IOMUXC_GPIO_LPSR_09_MIC_BITSTREAM0,     /* GPIO_LPSR_09 PAD functional properties : */
	  0x03U);                                 /* Slew Rate Field: Fast Slew Rate
												 Drive Strength Field: high driver
												 Pull / Keep Select Field: Pull Disable
												 Pull Up / Down Config. Field: Weak pull down
												 Open Drain LPSR Field: Disabled
												 Domain write protection: Both cores are allowed
												 Domain write protection lock: Neither of DWP bits is locked */

// HF MEMS - BITSTREAM1 - PDM
	IOMUXC_SetPinMux(
	  IOMUXC_GPIO_LPSR_10_MIC_BITSTREAM1,     /* GPIO_LPSR_10 is configured as MIC_BITSTREAM1 */
	  0U);                                    /* Software Input On Field: Input Path is determined by functionality */

	IOMUXC_SetPinConfig(
	  IOMUXC_GPIO_LPSR_10_MIC_BITSTREAM1,     /* GPIO_LPSR_10 PAD functional properties : */
	  0x03U);                                 /* Slew Rate Field: Fast Slew Rate
												 Drive Strength Field: high driver
												 Pull / Keep Select Field: Pull Disable
												 Pull Up / Down Config. Field: Weak pull down
												 Open Drain LPSR Field: Disabled
												 Domain write protection: Both cores are allowed
												 Domain write protection lock: Neither of DWP bits is locked */


	// SW SPI //
#if(0)
    IOMUXC_SetPinMux(
    		IOMUXC_GPIO_SD_B2_00_FLEXSPI1_B_DATA03,    /* GPIO_SD_B2_05 is configured as FLEXSPI1_A_DQS */
        1U);                                    /* Software Input On Field: Force input path of pad GPIO_SD_B2_05 */
    IOMUXC_SetPinMux(
    		IOMUXC_GPIO_SD_B2_01_FLEXSPI1_B_DATA02,  /* GPIO_SD_B2_06 is configured as FLEXSPI1_A_SS0_B */
        1U);                                    /* Software Input On Field: Force input path of pad GPIO_SD_B2_06 */
    IOMUXC_SetPinMux(
    		IOMUXC_GPIO_SD_B2_02_FLEXSPI1_B_DATA01,   /* GPIO_SD_B2_07 is configured as FLEXSPI1_A_SCLK */
        1U);                                    /* Software Input On Field: Force input path of pad GPIO_SD_B2_07 */
    IOMUXC_SetPinMux(
    		IOMUXC_GPIO_SD_B2_03_FLEXSPI1_B_DATA00,  /* GPIO_SD_B2_08 is configured as FLEXSPI1_A_DATA00 */
        1U);                                    /* Software Input On Field: Force input path of pad GPIO_SD_B2_08 */
    IOMUXC_SetPinMux(
    		IOMUXC_GPIO_SD_B2_04_FLEXSPI1_B_SCLK,  /* GPIO_SD_B2_09 is configured as FLEXSPI1_A_DATA01 */
        1U);                                    /* Software Input On Field: Force input path of pad GPIO_SD_B2_09 */
    IOMUXC_SetPinMux(
    		IOMUXC_GPIO_SD_B2_05_FLEXSPI1_B_SS0_B,  /* GPIO_SD_B2_10 is configured as FLEXSPI1_A_DATA02 */
        1U);                                    /* Software Input On Field: Force input path of pad GPIO_SD_B2_10 */
#endif
    IOMUXC_SetPinMux(
    		IOMUXC_GPIO_SD_B2_00_GPIO10_IO09,    /* GPIO_SD_B2_05 is configured as FLEXSPI1_A_DQS */
        1U);                                    /* Software Input On Field: Force input path of pad GPIO_SD_B2_05 */
    IOMUXC_SetPinMux(
    		IOMUXC_GPIO_SD_B2_01_GPIO10_IO10,  /* GPIO_SD_B2_06 is configured as FLEXSPI1_A_SS0_B */
        1U);                                    /* Software Input On Field: Force input path of pad GPIO_SD_B2_06 */
    IOMUXC_SetPinMux(
    		IOMUXC_GPIO_SD_B2_02_GPIO10_IO11,   /* GPIO_SD_B2_07 is configured as FLEXSPI1_A_SCLK */
        1U);                                    /* Software Input On Field: Force input path of pad GPIO_SD_B2_07 */
    IOMUXC_SetPinMux(
    		IOMUXC_GPIO_SD_B2_03_GPIO10_IO12,  /* GPIO_SD_B2_08 is configured as FLEXSPI1_A_DATA00 */
        1U);                                    /* Software Input On Field: Force input path of pad GPIO_SD_B2_08 */
    IOMUXC_SetPinMux(
    		IOMUXC_GPIO_SD_B2_04_GPIO10_IO13,  /* GPIO_SD_B2_09 is configured as FLEXSPI1_A_DATA01 */
        1U);                                    /* Software Input On Field: Force input path of pad GPIO_SD_B2_09 */

    // You need to burn fuse: FLEX_SPI_PIN_SEL at bit 11 of fuse 0x9A0 to use the following GPIO pin.
    // note that you then must turn on the DQS pin on EMC_B2_18 prior to switching to over the SD_B2_05 pin.  The
    // commands below do this in the correct order.  If you perform this the other way around, your program won't
    // execute correctly.  T.S. 2023 05 30

    IOMUXC_SetPinMux(
    		IOMUXC_GPIO_EMC_B2_18_FLEXSPI1_A_DQS ,  /* */
        1U);                                        /* */
    IOMUXC_SetPinMux(
    		IOMUXC_GPIO_SD_B2_05_GPIO10_IO14,  /* GPIO_SD_B2_10 is configured as FLEXSPI1_A_DATA02 */
        1U);                                    /* Software Input On Field: Force input path of pad GPIO_SD_B2_10 */


	EFUSE_A_SHUTDOWN_UN_ASSERT;
	EFUSE_A_SHUTDOWN_UN_ASSERT;
	LED_OFF_ALL;
	PHY_RESET_UNASSERT;
	DIAG_E8_OFF;
	LED_ARRAY_STROBE_ON;
	LED_ARRAY_CHARGE_ON;


}











/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
BOARD_InitEnetPins:
- options: {callFromInitBoot: 'false', coreID: cm7, enableClock: 'true'}
- pin_list:
  - {pin_num: P17, peripheral: GPIO9, signal: 'gpio_io, 11', pin_signal: GPIO_AD_12}
  - {pin_num: K16, peripheral: ENET, signal: enet_mdc, pin_signal: GPIO_AD_32}
  - {pin_num: H17, peripheral: ENET, signal: enet_mdio, pin_signal: GPIO_AD_33}
  - {pin_num: E9, peripheral: ENET, signal: 'enet_tdata, 00', pin_signal: GPIO_DISP_B2_02}
  - {pin_num: D7, peripheral: ENET, signal: 'enet_tdata, 01', pin_signal: GPIO_DISP_B2_03}
  - {pin_num: C7, peripheral: ENET, signal: enet_tx_en, pin_signal: GPIO_DISP_B2_04}
  - {pin_num: C9, peripheral: ENET, signal: enet_ref_clk, pin_signal: GPIO_DISP_B2_05, software_input_on: Enable, slew_rate: Fast}
  - {pin_num: C6, peripheral: ENET, signal: 'enet_rdata, 00', pin_signal: GPIO_DISP_B2_06}
  - {pin_num: D6, peripheral: ENET, signal: 'enet_rdata, 01', pin_signal: GPIO_DISP_B2_07}
  - {pin_num: B5, peripheral: ENET, signal: enet_rx_en, pin_signal: GPIO_DISP_B2_08}
  - {pin_num: D8, peripheral: ENET, signal: enet_rx_er, pin_signal: GPIO_DISP_B2_09}
  - {pin_num: U5, peripheral: GPIO12, signal: 'gpio_io, 12', pin_signal: GPIO_LPSR_12}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitEnetPins, assigned for the Cortex-M7F core.
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void BOARD_InitEnetPins(void) {
  CLOCK_EnableClock(kCLOCK_Iomuxc);           /* LPCG on: LPCG is ON. */
  CLOCK_EnableClock(kCLOCK_Iomuxc_Lpsr);      /* LPCG on: LPCG is ON. */

  CLOCK_EnableClock(kCLOCK_Iomuxc);           /* LPCG on: LPCG is ON. */
  CLOCK_EnableClock(kCLOCK_Iomuxc_Lpsr);      /* LPCG on: LPCG is ON. */

//  IOMUXC_SetPinMux(					// ts.
//      IOMUXC_GPIO_AD_30_GPIO9_IO29,             /* GPIO_AD_32 is configured as ENET_MDC */
//      0U);


  IOMUXC_SetPinMux(
      IOMUXC_GPIO_AD_12_GPIO9_IO11,           /* GPIO_AD_12 is configured as GPIO9_IO11 */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
//  IOMUXC_SetPinMux(
//      IOMUXC_GPIO_AD_32_ENET_MDC,             /* GPIO_AD_32 is configured as ENET_MDC */
//      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
//  IOMUXC_SetPinMux(
//      IOMUXC_GPIO_AD_33_ENET_MDIO,            /* GPIO_AD_33 is configured as ENET_MDIO */
//      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
//  IOMUXC_SetPinMux(
//      IOMUXC_GPIO_DISP_B2_02_ENET_TX_DATA00,  /* GPIO_DISP_B2_02 is configured as ENET_TX_DATA00 */
//      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
//  IOMUXC_SetPinMux(
//      IOMUXC_GPIO_DISP_B2_03_ENET_TX_DATA01,  /* GPIO_DISP_B2_03 is configured as ENET_TX_DATA01 */
//      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
//  IOMUXC_SetPinMux(
//      IOMUXC_GPIO_DISP_B2_04_ENET_TX_EN,      /* GPIO_DISP_B2_04 is configured as ENET_TX_EN */
//      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
//  IOMUXC_SetPinMux(
//      IOMUXC_GPIO_DISP_B2_05_ENET_REF_CLK,    /* GPIO_DISP_B2_05 is configured as ENET_REF_CLK */
//      1U);                                    /* Software Input On Field: Force input path of pad GPIO_DISP_B2_05 */
//  IOMUXC_SetPinMux(
//      IOMUXC_GPIO_DISP_B2_06_ENET_RX_DATA00,  /* GPIO_DISP_B2_06 is configured as ENET_RX_DATA00 */
//      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
//  IOMUXC_SetPinMux(
//      IOMUXC_GPIO_DISP_B2_07_ENET_RX_DATA01,  /* GPIO_DISP_B2_07 is configured as ENET_RX_DATA01 */
 //     0U);                                    /* Software Input On Field: Input Path is determined by functionality */
//  IOMUXC_SetPinMux(
//      IOMUXC_GPIO_DISP_B2_08_ENET_RX_EN,      /* GPIO_DISP_B2_08 is configured as ENET_RX_EN */
//      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
//  IOMUXC_SetPinMux(
//      IOMUXC_GPIO_DISP_B2_09_ENET_RX_ER,      /* GPIO_DISP_B2_09 is configured as ENET_RX_ER */
//      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_GPR->GPR4 = ((IOMUXC_GPR->GPR4 &
    (~(IOMUXC_GPR_GPR4_ENET_REF_CLK_DIR_MASK))) /* Mask bits to zero which are setting */
      | IOMUXC_GPR_GPR4_ENET_REF_CLK_DIR(0x01U) /* ENET_REF_CLK direction control: 0x01U */
    );
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_LPSR_12_GPIO12_IO12,        /* GPIO_LPSR_12 is configured as GPIO12_IO12 */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
//  IOMUXC_SetPinConfig(
//      IOMUXC_GPIO_DISP_B2_05_ENET_REF_CLK,    /* GPIO_DISP_B2_05 PAD functional properties : */
 //     0x03U);                                 /* Slew Rate Field: Fast Slew Rate
//                                                 Drive Strength Field: high drive strength
//                                                 Pull / Keep Select Field: Pull Disable, Highz
//                                                 Pull Up / Down Config. Field: Weak pull down
//                                                 Open Drain Field: Disabled
//                                                 Domain write protection: Both cores are allowed
//                                                 Domain write protection lock: Neither of DWP bits is locked */


}


/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
BOARD_InitEnet1GPins:
- options: {callFromInitBoot: 'false', coreID: cm7, enableClock: 'true'}
- pin_list:
  - {pin_num: E13, peripheral: ENET_1G, signal: enet_rx_en, pin_signal: GPIO_DISP_B1_00}
  - {pin_num: D13, peripheral: ENET_1G, signal: enet_rx_clk, pin_signal: GPIO_DISP_B1_01}
  - {pin_num: D11, peripheral: ENET_1G, signal: 'enet_rdata, 00', pin_signal: GPIO_DISP_B1_02}
  - {pin_num: E11, peripheral: ENET_1G, signal: 'enet_rdata, 01', pin_signal: GPIO_DISP_B1_03}
  - {pin_num: E10, peripheral: ENET_1G, signal: 'enet_rdata, 02', pin_signal: GPIO_DISP_B1_04}
  - {pin_num: C11, peripheral: ENET_1G, signal: 'enet_rdata, 03', pin_signal: GPIO_DISP_B1_05}
  - {pin_num: D10, peripheral: ENET_1G, signal: 'enet_tdata, 03', pin_signal: GPIO_DISP_B1_06}
  - {pin_num: E12, peripheral: ENET_1G, signal: 'enet_tdata, 02', pin_signal: GPIO_DISP_B1_07}
  - {pin_num: A15, peripheral: ENET_1G, signal: 'enet_tdata, 01', pin_signal: GPIO_DISP_B1_08}
  - {pin_num: C13, peripheral: ENET_1G, signal: 'enet_tdata, 00', pin_signal: GPIO_DISP_B1_09}
  - {pin_num: B14, peripheral: ENET_1G, signal: enet_tx_en, pin_signal: GPIO_DISP_B1_10}
  - {pin_num: A14, peripheral: ENET_1G, signal: enet_tx_clk_io, pin_signal: GPIO_DISP_B1_11}
  - {pin_num: A5, peripheral: GPIO11, signal: 'gpio_io, 14', pin_signal: GPIO_DISP_B2_13}
  - {pin_num: U2, peripheral: ENET_1G, signal: enet_mdc, pin_signal: GPIO_EMC_B2_19}
  - {pin_num: R3, peripheral: ENET_1G, signal: enet_mdio, pin_signal: GPIO_EMC_B2_20}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitEnet1GPins, assigned for the Cortex-M7F core.
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void BOARD_InitEnet1GPins(void) {
  CLOCK_EnableClock(kCLOCK_Iomuxc);           /* LPCG on: LPCG is ON. */

  IOMUXC_SetPinMux(
      IOMUXC_GPIO_DISP_B1_00_ENET_1G_RX_EN,   /* GPIO_DISP_B1_00 is configured as ENET_1G_RX_EN */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_DISP_B1_01_ENET_1G_RX_CLK,  /* GPIO_DISP_B1_01 is configured as ENET_1G_RX_CLK */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_DISP_B1_02_ENET_1G_RX_DATA00,  /* GPIO_DISP_B1_02 is configured as ENET_1G_RX_DATA00 */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_DISP_B1_03_ENET_1G_RX_DATA01,  /* GPIO_DISP_B1_03 is configured as ENET_1G_RX_DATA01 */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_DISP_B1_04_ENET_1G_RX_DATA02,  /* GPIO_DISP_B1_04 is configured as ENET_1G_RX_DATA02 */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_DISP_B1_05_ENET_1G_RX_DATA03,  /* GPIO_DISP_B1_05 is configured as ENET_1G_RX_DATA03 */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_DISP_B1_06_ENET_1G_TX_DATA03,  /* GPIO_DISP_B1_06 is configured as ENET_1G_TX_DATA03 */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_DISP_B1_07_ENET_1G_TX_DATA02,  /* GPIO_DISP_B1_07 is configured as ENET_1G_TX_DATA02 */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_DISP_B1_08_ENET_1G_TX_DATA01,  /* GPIO_DISP_B1_08 is configured as ENET_1G_TX_DATA01 */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_DISP_B1_09_ENET_1G_TX_DATA00,  /* GPIO_DISP_B1_09 is configured as ENET_1G_TX_DATA00 */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_DISP_B1_10_ENET_1G_TX_EN,   /* GPIO_DISP_B1_10 is configured as ENET_1G_TX_EN */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_DISP_B1_11_ENET_1G_TX_CLK_IO,  /* GPIO_DISP_B1_11 is configured as ENET_1G_TX_CLK_IO */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_DISP_B2_13_GPIO11_IO14,     /* GPIO_DISP_B2_13 is configured as GPIO11_IO14 */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_EMC_B2_19_ENET_1G_MDC,      /* GPIO_EMC_B2_19 is configured as ENET_1G_MDC */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_EMC_B2_20_ENET_1G_MDIO,     /* GPIO_EMC_B2_20 is configured as ENET_1G_MDIO */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
}

void BOARD_InitMicPins(void) {
  CLOCK_EnableClock(kCLOCK_Iomuxc_Lpsr);      /* LPCG on: LPCG is ON. */

  IOMUXC_SetPinMux(
      IOMUXC_GPIO_LPSR_08_MIC_CLK,            /* GPIO_LPSR_08 is configured as MIC_CLK */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_LPSR_09_MIC_BITSTREAM0,     /* GPIO_LPSR_09 is configured as MIC_BITSTREAM0 */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
	  IOMUXC_GPIO_LPSR_10_MIC_BITSTREAM1,     /* GPIO_LPSR_10 is configured as MIC_BITSTREAM1 */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinConfig(
      IOMUXC_GPIO_LPSR_08_MIC_CLK,            /* GPIO_LPSR_08 PAD functional properties : */
      0x03U);                                 /* Slew Rate Field: Fast Slew Rate
                                                 Drive Strength Field: high driver
                                                 Pull / Keep Select Field: Pull Disable
                                                 Pull Up / Down Config. Field: Weak pull down
                                                 Open Drain LPSR Field: Disabled
                                                 Domain write protection: Both cores are allowed
                                                 Domain write protection lock: Neither of DWP bits is locked */
  IOMUXC_SetPinConfig(
      IOMUXC_GPIO_LPSR_09_MIC_BITSTREAM0,     /* GPIO_LPSR_09 PAD functional properties : */
      0x03U);                                 /* Slew Rate Field: Fast Slew Rate
                                                 Drive Strength Field: high driver
                                                 Pull / Keep Select Field: Pull Disable
                                                 Pull Up / Down Config. Field: Weak pull down
                                                 Open Drain LPSR Field: Disabled
                                                 Domain write protection: Both cores are allowed
                                                 Domain write protection lock: Neither of DWP bits is locked */
  IOMUXC_SetPinConfig(
      IOMUXC_GPIO_LPSR_10_MIC_BITSTREAM1,     /* GPIO_LPSR_11 PAD functional properties : */
      0x03U);                                 /* Slew Rate Field: Fast Slew Rate
                                                 Drive Strength Field: high driver
                                                 Pull / Keep Select Field: Pull Disable
                                                 Pull Up / Down Config. Field: Weak pull down
                                                 Open Drain LPSR Field: Disabled
                                                 Domain write protection: Both cores are allowed
                                                 Domain write protection lock: Neither of DWP bits is locked */
}

/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
