/*
 * Copyright 2020-2021 NXP
 * All rights reserved.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 */

/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PIN_MUX_H_
#define _PIN_MUX_H_

/*!
 * @addtogroup pin_mux
 * @{
 */

/***********************************************************************************************************************
 * API
 **********************************************************************************************************************/

#if defined(__cplusplus)
extern "C" {
#endif

/* GPIO_DISP_B2_13 (coord A5), INT1_COMBO/BT_UART_RTS/U16[4]/U354[5]/ETHPHY_RST_B/U10[12] */
/* Routed pin properties */
#define BOARD_INITPINS_CAMERA_FREX_PERIPHERAL                              GPIO5   /*!< Peripheral name */
#define BOARD_INITPINS_CAMERA_FREX_SIGNAL                            gpio_mux_io   /*!< Signal name */
#define BOARD_INITPINS_CAMERA_FREX_CHANNEL                                   14U   /*!< Signal channel */

/* GPIO_DISP_B2_14 (coord A7), INT2_COMBO/CSI_RST_B */
/* Routed pin properties */
#define BOARD_INITPINS_CAMERA_RESET_PERIPHERAL                             GPIO5   /*!< Peripheral name */
#define BOARD_INITPINS_CAMERA_RESET_SIGNAL                           gpio_mux_io   /*!< Signal name */
#define BOARD_INITPINS_CAMERA_RESET_CHANNEL                                  15U   /*!< Signal channel */

/* GPIO_AD_20 (coord K13), SAI1_RXD[0]/J9[7]/J50[20]/J61[1]/BT_PCM_RXD/U16[10]/U355[18] */
/* Routed pin properties */
#define BOARD_INITPINS_CAMERA_VSYNC_PERIPHERAL                             GPIO3   /*!< Peripheral name */
#define BOARD_INITPINS_CAMERA_VSYNC_SIGNAL                           gpio_mux_io   /*!< Signal name */
#define BOARD_INITPINS_CAMERA_VSYNC_CHANNEL                                  19U   /*!< Signal channel */

/* GPIO_AD_21 (coord K14), SAI1_TXD[0]/J9[9]/J62[1]/BT_PCM_TXD/U16[9]/U354[6] */
/* Routed pin properties */
#define BOARD_INITPINS_CAMERA_STROBE_TO_UC_PERIPHERAL                      GPIO3   /*!< Peripheral name */
#define BOARD_INITPINS_CAMERA_STROBE_TO_UC_SIGNAL                    gpio_mux_io   /*!< Signal name */
#define BOARD_INITPINS_CAMERA_STROBE_TO_UC_CHANNEL                           20U   /*!< Signal channel */

/* GPIO_AD_23 (coord J12), SAI1_TX_SYNC/J9[13]/BT_PCM_SYNC/U16[8]/U354[8]/U355[16] */
/* Routed pin properties */
#define BOARD_INITPINS_UC_STROBE_PERIPHERAL                                GPIO3   /*!< Peripheral name */
#define BOARD_INITPINS_UC_STROBE_SIGNAL                              gpio_mux_io   /*!< Signal name */
#define BOARD_INITPINS_UC_STROBE_CHANNEL                                     22U   /*!< Signal channel */

/* GPIO_AD_24 (coord L13), LPUART1_TXD/J31[2] */
/* Routed pin properties */
#define BOARD_INITPINS_CAMERA_SHUTTER_RESET_PERIPHERAL                     GPIO3   /*!< Peripheral name */
#define BOARD_INITPINS_CAMERA_SHUTTER_RESET_SIGNAL                   gpio_mux_io   /*!< Signal name */
#define BOARD_INITPINS_CAMERA_SHUTTER_RESET_CHANNEL                          23U   /*!< Signal channel */

/* GPIO_AD_25 (coord M15), LPUART1_RXD/J32[2] */
/* Routed pin properties */
#define BOARD_INITPINS_CAMERA_SHUTTER_SET_PERIPHERAL                       GPIO3   /*!< Peripheral name */
#define BOARD_INITPINS_CAMERA_SHUTTER_SET_SIGNAL                     gpio_mux_io   /*!< Signal name */
#define BOARD_INITPINS_CAMERA_SHUTTER_SET_CHANNEL                            24U   /*!< Signal channel */

/* GPIO_AD_26 (coord L14), CSI_PWR_CTL/USER_LED_CTL2/J50[16] */
/* Routed pin properties */
#define BOARD_INITPINS_CAMERA_PWR_CTL_1V8_PERIPHERAL                       GPIO3   /*!< Peripheral name */
#define BOARD_INITPINS_CAMERA_PWR_CTL_1V8_SIGNAL                     gpio_mux_io   /*!< Signal name */
#define BOARD_INITPINS_CAMERA_PWR_CTL_1V8_CHANNEL                            25U   /*!< Signal channel */


/*!
 * @brief Calls initialization functions.
 *
 */
void BOARD_InitBootPins(void);

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitPins(void);                    /* Function assigned for the Cortex-M7F */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitEnetPins(void);                /* Function assigned for the Cortex-M7F */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitEnet1GPins(void);              /* Function assigned for the Cortex-M7F */

void BOARD_InitMicPins(void);                 /* Function assigned for the Cortex-M7F */

#if defined(__cplusplus)
}
#endif

/*!
 * @}
 */
#endif /* _PIN_MUX_H_ */

/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
